# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ACBDEM
                                 A QGIS plugin
 Este plugin crea y procesa Modelos Digitales del Terreno
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-10-21
        copyright            : (C) 2023 by Antonio Carlos Benavides García. Máster en Geotecnologías Cartográficas para Ingeniería y Arquitectura. Universidad de Salamanca
        email                : antonio.benavides@usal.es
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ACBDEM class from file ACBDEM.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ACB_DEM import ACBDEM
    return ACBDEM(iface)
